### PR TITLE
update pd dependencies

### PR DESCRIPTION
**Pull request by HunDunDM**
### What problem does this PR solve? 

This PR is the stage 1 of https://github.com/pingcap/tidb/issues/19306 , in order to upgrade the PD dependency of tidb related repo.

**Note**: After merging this PR, it will temporarily be unable to compile.

### CODE REVIEW

**Comment by coocood** [comment]
```
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0001bcb90, 0xc00007cbb0, 0x1, 0x1)
	/Users/zhou/gopath/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:400 +0xad
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/Users/zhou/gopath/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:177
github.com/pingcap/pd/v4/client.init.0()
	/Users/zhou/gopath/pkg/mod/github.com/pingcap/pd/v4@v4.0.0-rc.2.0.20200730093003-dc8c75cf7ca0/client/metrics.go:85 +0x91
```
maybe we need to remove the MustRegister in pd client init function?

**Comment by HunDunDM** [comment]
This is because the current project still indirectly depends on `pingcap/pd/v4` because of `tidb` dependency, which will be resolved in stage 3.

**Comment by coocood** [comment]
If tikv/pd/client remove the register, we can upgrade smoothly.

**Comment by HunDunDM** [comment]
Relying on two versions of PD is not expected behavior. We always need the stage 3 PR to update tidb.

**Comment by coocood** [comment]
My point is that we better not break the build during the upgrade process.

**Comment by coocood** [comment]
Or we can create a branch of tikv pd client that doesn't register, used for repos depends on pingcap pd.

**Comment by HunDunDM** [comment]
Will be merge to the `update-pd-tmp` branch

**Pull request closed without merging**
