### PR TITLE
refactor test util, port txn tests from tikv

### PR DESCRIPTION
**Pull request by cfzjywxk**
~~1. Add item length check for `dbReader.get` (item.Value could be non nil zero length slice)~~
2. Port some basic txn tests from tikv(current  tikv package coverage 22.1 %)
3. Refactor some test functions and make them clean

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@coocood @bobotu PTAL

**Comment by bobotu** [comment]
We can make badger treat `nil` and `zero-length slice` as the different values if needed. I think it will need a new flag in entry's underlaying metadata? @cfzjywxk

**Comment by cfzjywxk** [comment]
> We can make badger treat `nil` and `zero-length slice` as the different values if needed. I think it need a new flag in entry's underlaying metadata? @cfzjywxk
@bobotu 

@coocood Advised using `len(item.Value()) == 0` to judge if it's empty but not using `val == nil`

**Comment by cfzjywxk** [comment]
@coocood PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
